# Generated by Django 6.0.1 on 2026-01-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 일시'),
        ),
    ]
