# Generated by Django 6.0.1 on 2026-01-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_last_login_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(max_length=100, verbose_name="검색 키워드"),
                ),
                (
                    "searched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="검색 일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_search_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "장소 검색 기록",
                "verbose_name_plural": "장소 검색 기록 목록",
                "db_table": "place_search_history",
                "ordering": ["-searched_at"],
            },
        ),
    ]
