# Generated by Django 6.0.1 on 2026-01-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_placesearchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceSearchHistory',
        ),
    ]
