# Generated by Django 6.0.1 on 2026-01-13 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.CharField(max_length=50, verbose_name='출발지 경도')),
                ('start_y', models.CharField(max_length=50, verbose_name='출발지 위도')),
                ('end_x', models.CharField(max_length=50, verbose_name='도착지 경도')),
                ('end_y', models.CharField(max_length=50, verbose_name='도착지 위도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
            ],
            options={
                'verbose_name': '경로 탐색 결과',
                'verbose_name_plural': '경로 탐색 결과 목록',
                'db_table': 'route_itinerary',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchItineraryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_name', models.CharField(blank=True, default='', max_length=255, verbose_name='출발지명')),
                ('arrival_name', models.CharField(blank=True, default='', max_length=255, verbose_name='도착지명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('route_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to='itineraries.routeitinerary', verbose_name='경로 탐색 결과')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_histories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '경로 검색 기록',
                'verbose_name_plural': '경로 검색 기록 목록',
                'db_table': 'search_itinerary_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_index', models.PositiveIntegerField(verbose_name='경로 인덱스')),
                ('path_type', models.PositiveSmallIntegerField(verbose_name='경로 타입')),
                ('total_time', models.PositiveIntegerField(verbose_name='총 소요시간 (초)')),
                ('total_distance', models.PositiveIntegerField(verbose_name='총 이동거리 (m)')),
                ('total_walk_time', models.PositiveIntegerField(default=0, verbose_name='총 도보 소요시간 (초)')),
                ('total_walk_distance', models.PositiveIntegerField(default=0, verbose_name='총 도보 이동거리 (m)')),
                ('transfer_count', models.PositiveSmallIntegerField(default=0, verbose_name='환승 횟수')),
                ('total_fare', models.PositiveIntegerField(default=0, verbose_name='총 요금')),
                ('raw_data', models.JSONField(verbose_name='TMAP API 원본 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('route_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='itineraries.routeitinerary', verbose_name='경로 탐색 결과')),
            ],
            options={
                'verbose_name': '경로 구간',
                'verbose_name_plural': '경로 구간 목록',
                'db_table': 'route_leg',
                'ordering': ['route_itinerary', 'leg_index'],
                'unique_together': {('route_itinerary', 'leg_index')},
            },
        ),
    ]
