# Generated by Django 6.0.1 on 2026-01-13 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.PositiveIntegerField(verbose_name='구간 인덱스')),
                ('mode', models.CharField(choices=[('WALK', '도보'), ('SUBWAY', '지하철'), ('BUS', '버스'), ('EXPRESSBUS', '고속버스'), ('TRAIN', '기차'), ('AIRPLANE', '항공'), ('FERRY', '해운')], max_length=20, verbose_name='이동수단')),
                ('section_time', models.PositiveIntegerField(verbose_name='소요시간 (초)')),
                ('distance', models.PositiveIntegerField(verbose_name='이동거리 (m)')),
                ('start_name', models.CharField(max_length=255, verbose_name='출발지명')),
                ('start_lat', models.FloatField(verbose_name='출발지 위도')),
                ('start_lon', models.FloatField(verbose_name='출발지 경도')),
                ('end_name', models.CharField(max_length=255, verbose_name='도착지명')),
                ('end_lat', models.FloatField(verbose_name='도착지 위도')),
                ('end_lon', models.FloatField(verbose_name='도착지 경도')),
                ('route_name', models.CharField(blank=True, default='', max_length=100, verbose_name='노선명')),
                ('route_color', models.CharField(blank=True, default='', max_length=10, verbose_name='노선 색상 (HEX)')),
                ('path_coordinates', models.JSONField(blank=True, help_text='[[lon, lat], [lon, lat], ...] 형태의 좌표 배열', null=True, verbose_name='경로 좌표 리스트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('route_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='itineraries.routeleg', verbose_name='경로 옵션')),
            ],
            options={
                'verbose_name': '경로 세부 구간',
                'verbose_name_plural': '경로 세부 구간 목록',
                'db_table': 'route_segment',
                'ordering': ['route_leg', 'segment_index'],
                'unique_together': {('route_leg', 'segment_index')},
            },
        ),
    ]
