# Generated by Django 6.0.1 on 2026-01-14 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0002_routesegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='봇 이름')),
                ('type', models.CharField(choices=[('rabbit', '토끼'), ('cat', '고양이'), ('dog', '강아지'), ('monkey', '원숭이')], default='rabbit', max_length=20, verbose_name='봇 타입 (생김새)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
            ],
            options={
                'verbose_name': '봇',
                'verbose_name_plural': '봇 목록',
                'db_table': 'bot',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('USER', '유저'), ('BOT', '봇')], max_length=10, verbose_name='참가자 유형')),
                ('status', models.CharField(choices=[('RUNNING', '진행중'), ('FINISHED', '완료'), ('CANCELED', '취소')], default='RUNNING', max_length=20, verbose_name='경주 상태')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='소요 시간 (초)')),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='순위')),
                ('is_win', models.BooleanField(blank=True, null=True, verbose_name='승리 여부')),
                ('start_lat', models.FloatField(blank=True, null=True, verbose_name='출발 위도')),
                ('start_lon', models.FloatField(blank=True, null=True, verbose_name='출발 경도')),
                ('end_lat', models.FloatField(blank=True, null=True, verbose_name='도착 위도')),
                ('end_lon', models.FloatField(blank=True, null=True, verbose_name='도착 경도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routes.bot', verbose_name='봇')),
                ('route_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='itineraries.routeitinerary', verbose_name='경로 탐색 결과')),
                ('route_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='itineraries.routeleg', verbose_name='배정된 경로')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '경주',
                'verbose_name_plural': '경주 목록',
                'db_table': 'route',
                'ordering': ['-created_at'],
            },
        ),
    ]
