# Generated by Django 6.0.1 on 2026-01-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=20, verbose_name='전철역 코드')),
                ('station_name', models.CharField(db_index=True, max_length=50, verbose_name='전철역명')),
                ('line', models.CharField(max_length=20, verbose_name='호선')),
                ('line_num', models.PositiveSmallIntegerField(db_index=True, verbose_name='호선 번호')),
                ('external_code', models.CharField(max_length=20, verbose_name='외부코드')),
                ('external_code_num', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='외부코드 숫자')),
            ],
            options={
                'verbose_name': '지하철 역',
                'verbose_name_plural': '지하철 역 목록',
                'db_table': 'subway_station',
                'indexes': [models.Index(fields=['station_name', 'line_num'], name='subway_stat_station_33f8a7_idx')],
            },
        ),
    ]
