# Generated by Django 6.0.1 on 2026-01-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_add_subway_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="type",
            field=models.CharField(
                choices=[
                    ("green", "초록"),
                    ("pink", "분홍"),
                    ("yellow", "노랑"),
                    ("purple", "보라"),
                ],
                default="purple",
                max_length=20,
                verbose_name="봇 타입 (색깔)",
            ),
        ),
    ]
