# Generated by Django 6.0.1 on 2026-01-14 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("home", "집"), ("work", "회사"), ("school", "학교")],
                        help_text="집(home), 회사(work), 학교(school) 또는 일반 즐겨찾기(null)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="사용자 지정 이름", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft Delete 타임스탬프", null=True
                    ),
                ),
                (
                    "poi_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="places.poiplace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_places",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_place",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("user", "poi_place"),
                        name="unique_active_saved_place",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("category__isnull", False), ("deleted_at__isnull", True)
                        ),
                        fields=("user", "category"),
                        name="unique_active_category_per_user",
                    ),
                ],
            },
        ),
    ]
