# Generated by Django 6.0.1 on 2026-01-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_savedplace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedplace",
            name="name",
        ),
    ]
