# Generated by Django 6.0.1 on 2026-01-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_savedplace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchplacehistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchplacehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
