# Generated by Django 6.0.1 on 2026-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_searchplacehistory_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiplace',
            name='tmap_pkey',
            # 1단계: 기존 데이터가 있으므로 우선 nullable/비-unique로 추가
            # (백필 이후 다음 마이그레이션에서 unique + not null로 강화)
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='poiplace',
            name='tmap_poi_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
