# Generated by Django 6.0.1 on 2026-01-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_searchplacehistory_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiplace',
            name='tmap_pkey',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='poiplace',
            name='tmap_poi_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
