# Generated by Django 6.0.1 on 2026-01-21

from django.db import migrations, models


def backfill_tmap_pkey(apps, schema_editor):
    """
    기존 poi_place 레코드들은 tmap_pkey가 없으므로(null/''), 유니크하게 채운다.
    - legacy-{id} 형태로 채우면 반드시 유니크하며, 이후 TMap에서 내려오는 실제 pkey와도 충돌 가능성이 낮다.
    """
    PoiPlace = apps.get_model("places", "PoiPlace")

    # null 또는 빈 문자열인 경우만 채움
    qs = PoiPlace.objects.filter(models.Q(tmap_pkey__isnull=True) | models.Q(tmap_pkey=""))
    for obj in qs.only("id", "tmap_pkey"):
        obj.tmap_pkey = f"legacy-{obj.id}"
        obj.save(update_fields=["tmap_pkey"])


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_add_tmap_pkey"),
    ]

    operations = [
        migrations.RunPython(backfill_tmap_pkey, migrations.RunPython.noop),
        # 2단계: 백필 이후 not null + unique로 강화
        migrations.AlterField(
            model_name="poiplace",
            name="tmap_pkey",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]

