# Generated by Django 6.0.1 on 2026-01-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_add_tmap_pkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poiplace',
            name='tmap_pkey',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
