# Generated by Django 6.0.1 on 2026-01-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # 원래는 두 개의 0006 마이그레이션을 머지하기 위해 생성되었으나,
        # 현재 코드베이스에는 `0006_backfill_tmap_pkey_and_enforce_unique` 만 존재한다.
        # 존재하지 않는 `0006_alter_poiplace_tmap_pkey`를 참조하면
        # Migration graph 로딩 시 NodeNotFoundError가 발생하므로
        # 의존성을 실제 존재하는 최신 마이그레이션 하나만 바라보도록 정리한다.
        ('places', '0006_backfill_tmap_pkey_and_enforce_unique'),
    ]

    operations = [
    ]
