# Generated by Django 6.0.1 on 2026-01-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_poiplace_tmap_pkey'),
        ('places', '0006_backfill_tmap_pkey_and_enforce_unique'),
    ]

    operations = [
    ]
