# Generated by Django 6.0.1 on 2026-01-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_alter_poiplace_tmap_pkey"),
        ("places", "0007_merge_20260121_1719"),
    ]

    operations = []
