# Generated by Django 6.0.1 on 2026-01-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_merge_20260122_1523"),
        ("places", "0008_merge_20260122_1651"),
    ]

    operations = []
